[package]
name = "pod-system"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pod-sdk = { path = "../pod-sdk" }
borsh = { version = "1", default-features = false, features = ["derive"] }

[profile.release]
opt-level = "s"
lto = true
